name: Build
on: 
  push:
    branches: 
      - develop
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build
        working-directory: src
      - run: dotnet test
        working-directory: src